---
- name:            Include OS-specific variables (Debian).
  include_vars:    "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:            ansible_os_family == 'Debian'

- name:            Include OS-specific variables (RedHat).
  include_vars:    "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when:            ansible_os_family == 'RedHat'

- name:            Install packages
  package:
    name:          "{{ _packages }}"
    state:         present

- name:            Ensure user's default shell is zsh
  user:
    name:          "{{ item.user_name }}"
    shell:         /bin/zsh
  loop:            "{{ ohmyzsh_users|flatten(levels=1) }}"

- name:            Include ohmyzsh tasks
  include_tasks:
    file:          ohmyzsh.yml
    apply:
      become:      yes
      become_user: "{{ loop_ohmyzsh_users.user_name }}"
  loop:            "{{ ohmyzsh_users|flatten(levels=1) }}"
  loop_control:
    loop_var:      loop_ohmyzsh_users
